# Generated by Django 3.2.12 on 2024-11-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_schedule_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='departure_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_schedules', to='train.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='train.schedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.user'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_schedules', to='train.destination'),
        ),
    ]
