# Generated by Django 3.2.12 on 2024-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_schedule_price_per_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
