# Generated by Django 3.2.12 on 2024-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='seats',
            field=models.JSONField(default=dict),
        ),
    ]
