# Generated by Django 3.2.12 on 2024-11-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_alter_schedule_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='email',
        ),
    ]
